# Generated by Django 5.0.6 on 2024-07-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finanza',
            name='tipo',
            field=models.CharField(choices=[('income', 'Ingreso'), ('spend', 'Gasto')], max_length=100),
        ),
    ]
