# Generated by Django 5.0.6 on 2024-07-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_finanza_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='finanza',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
