# Generated by Django 5.0.6 on 2024-07-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_finanza_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finanza',
            name='id_usuario',
            field=models.IntegerField(),
        ),
    ]
