# Generated by Django 5.0.6 on 2024-07-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_finanza_id_usuario'),
        ('finanzas', '0003_finanza_descripcion_finanza_motivo'),
    ]

    operations = [
    ]
